application: qopher
version: 1
runtime: go
api_version: go1

handlers:
- url: /static/(.*)
  static_files: static/\1
  upload: static/.*
- url: /_ah/queue/go/delay
  script: _go_app
  login: admin
- url: /(gc|admin)
  script: _go_app
  login: admin
- url: /.*
  script: _go_app
  login: required
